name: auth
port: 30000
deployment:
  replicas: 2
  env:
    CREATE_CLIENT_QUEUE: "CREATE_CLIENT_QUEUE"
    CREATE_EMPLOYEE_QUEUE: "CREATE_EMPLOYEE_QUEUE"
    CREATE_AUTHOR_QUEUE: "CREATE_AUTHOR_QUEUE"
authService: auth-service
public:
  - path: "/ping"
    method: "GET"
    id: "GET_PING"

  - path: "/health"
    method: "GET"
    id: "GET_HEALTH"

  - path: "/api/auth/client"
    method: "POST"
    id: "ADD_CLIENT"

  - path: "/api/auth/login"
    method: "POST"
    id: "LOGIN"

  - path: "/pingo/[a-z]*[^/]+$"
    method: "POST"
    id: "PostGia"
    prefix: "~ ^"

